name: lint test and build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - run: yarn install
      - uses: mansagroup/nrwl-nx-action@v2
        with:
          targets: lint,test,build
          affected: 'true'
